<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="antenna"
    params="parent_link xyz rpy
            tf_prefix:=None
            antenna_angle:=0.0">

    <xacro:if value="${tf_prefix == 'None'}">
      <xacro:property name="tf_prefix_ext" value="" />
    </xacro:if>
    <xacro:unless value="${tf_prefix == 'None'}">
      <xacro:property name="tf_prefix_ext" value="${tf_prefix}_" />
    </xacro:unless>

    <xacro:property name="antenna_length" value="0.1" />
    <xacro:property name="antenna_radius" value="0.0052" />

    <joint name="${parent_link.rstrip('_link')}_to_${tf_prefix_ext}antenna_connector_joint" type="fixed">
      <origin xyz="${xyz}" rpy="${rpy}" />
      <parent link="${parent_link}" />
      <child link="${tf_prefix_ext}antenna_connector_link" />
    </joint>

    <link name="${tf_prefix_ext}antenna_connector_link">
      <visual>
        <geometry>
          <mesh filename="package://rosbot_xl_description/meshes/components/antenna_connector.dae"
            scale="1 1 1" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </visual>
    </link>

    <joint name="${tf_prefix_ext}antenna_connector_to_${tf_prefix_ext}antenna_joint" type="fixed">
      <origin xyz="-0.013 0.0 0.008" rpy="0.0 ${antenna_angle} 0.0" />
      <parent link="${tf_prefix_ext}antenna_connector_link" />
      <child link="${tf_prefix_ext}antenna_link" />
    </joint>

    <link name="${tf_prefix_ext}antenna_link">
      <visual>
        <geometry>
          <mesh filename="package://rosbot_xl_description/meshes/components/antenna.dae"
            scale="1 1 1" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${antenna_radius}" length="${antenna_length}" />
        </geometry>
        <origin xyz="0.0 0.0 ${antenna_length/2.}" rpy="0.0 0.0 0.0" />
      </collision>
    </link>

  </xacro:macro>
</robot>
