# FROM osrf/ros:galactic-desktop
FROM rosbot_xl_simulation:latest

ARG user=husarion

RUN useradd -ms /bin/bash ${user} && \
    echo "$user:$user" | chpasswd && \
    adduser ${user} sudo && \
    echo "$user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ${user}
WORKDIR /home/${user}

RUN sudo apt-get update && \
    sudo apt-get install --no-install-recommends -y \
    nano gdb clang clang-format cppcheck bash-completion python3-pip htop && \
    /usr/bin/python3 -m pip install -U black --user

RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/${user}/.bashrc && \
    echo "source /home/$user/ros2_ws/install/setup.bash --extend" >> /home/${user}/.bashrc