---
  - topic_name: <robot_namespace><zed>/zed_node/rgb/camera_info
    ros_type_name: sensor_msgs/msg/CameraInfo
    gz_type_name: ignition.msgs.CameraInfo

  - topic_name: <robot_namespace><zed>/zed_node/rgb/image_rect_color
    ros_type_name: sensor_msgs/msg/Image
    gz_type_name: ignition.msgs.Image

  - ros_topic_name: <robot_namespace><zed>/zed_node/depth/camera_info
    gz_topic_name: <robot_namespace><zed>/zed_node/camera_info
    ros_type_name: sensor_msgs/msg/CameraInfo
    gz_type_name: ignition.msgs.CameraInfo

  - ros_topic_name: <robot_namespace><zed>/zed_node/depth/depth_registered
    gz_topic_name: <robot_namespace><zed>/zed_node/depth
    ros_type_name: sensor_msgs/msg/Image
    gz_type_name: ignition.msgs.Image

  - ros_topic_name: <robot_namespace><zed>/zed_node/point_cloud/cloud_registered
    gz_topic_name: <robot_namespace><zed>/zed_node/depth/points
    ros_type_name: sensor_msgs/msg/PointCloud2
    gz_type_name: ignition.msgs.PointCloudPacked
