---
name: Industrial CI
on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: --line-length=99

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rojopolis/spellcheck-github-actions@0.33.1
        name: Spellcheck

  ros_industrial_ci:
    name: ROS Industrial CI
    needs:
      - black
      - spellcheck
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ROS2 Workspace and Clone Repositories
        env:
          HUSARION_ROS_BUILD_TYPE: simulation
        run: |
          mkdir -p src
          find . -maxdepth 1 -not -name src -not -name . -exec mv {} src/ \;
          python3 -m pip install -U vcstool
          vcs import src < src/rosbot_xl/rosbot_xl_$HUSARION_ROS_BUILD_TYPE.repos
          cp -r src/ros2_controllers/diff_drive_controller src/
          cp -r src/ros2_controllers/imu_sensor_broadcaster src/
          rm -rf src/ros2_controllers

      - name: Leave only ROSbot tests
        shell: bash
        run: |
          sed '/if(BUILD_TESTING)/,/endif()/d' src/diff_drive_controller/CMakeLists.txt -i
          sed '/if(BUILD_TESTING)/,/endif()/d' src/imu_sensor_broadcaster/CMakeLists.txt -i
          # Package micro_ros_msgs does not have industrial ci and tests does not pass.
          # For more information see https://github.com/micro-ROS/micro_ros_msgs/issues/7
          sed '/if(BUILD_TESTING)/,/endif()/d' src/micro_ros_msgs/CMakeLists.txt -i

      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{matrix.ROS_DISTRO}}
          HUSARION_ROS_BUILD_TYPE: simulation
